import "./globals.css";

export const metadata = {
  title: "Graham",
  description: "Generated by Graham.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
