import "./globals.css";

export const metadata = {
  title: "Graham",
  description: "Generated by Graham.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center">
        <div className="w-1/2">{children}</div>
      </body>
    </html>
  );
}
